name: Lint

push:
  branches:
    - gh-pages
  paths:
    - 'js/*'
    - 'build.py'
    - '.eslintrc.js'

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Lint
      run: make lint
