name: Lint

on:
  push:
    branches:
      - gh-pages
    paths:
      - '**.js'
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Lint
      run: make lint
