name: Update revisions and PRs

#  schedule:
#    # Every 30 minutes
#    - cron:  '*/30 * * * *'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Get gh-pages hash
      run: |
        curl \
        --url https://api.github.com/repos/${{ github.repository }}/branches/gh-pages \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' | \
        python -c 'import sys; import json; print("##[set-output name=sha;]{}".format(json.loads(sys.stdin.read())["commit"]["sha"]))'
      id: hash
    - name: Download Bootstrap
      run: |
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/Makefile
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/build.py
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/config.json
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/revs.json
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/prs.json
        curl -O https://raw.githubusercontent.com/${{github.repository}}/${{steps.hash.outputs.sha}}/requirements.txt
    - name: Setup virtualenv
      run: make py-venv-bootstrap
    - name: Run Bootstrap
      run: make bootstrap
      id: bootstrap
    - name: Remove bootstrp
      run: |
        rm Makefile
        rm build.py
        rm config.json
        rm revs.json
        rm prs.json
        rm requirements.txt
    - name: Checkout
      if: steps.bootstrap.outputs.update == 'Yes'
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Setup virtualenv
      if: steps.bootstrap.outputs.update == 'Yes'
      run: make py-venv
    - name: Clone ecma262
      if: steps.bootstrap.outputs.update == 'Yes'
      run: make clone
    - name: Update revisions
      if: steps.bootstrap.outputs.update_revs == 'Yes'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: make update5
    - name: Update PRs
      if: steps.bootstrap.outputs.update_prs == 'Yes'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: make pr5
    - name: Commit files
      # fails if no files to commit
      continue-on-error: true
      if: steps.bootstrap.outputs.update == 'Yes'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add history
        git add revs.js
        git add prs.js
        git commit -m "update history"
    - name: Push changes
      # fails if no files to commit
      continue-on-error: true
      if: steps.bootstrap.outputs.update == 'Yes'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: false
